//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.DBAToolbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zen.DBAToolbox.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CaseSchema SchemaID=&quot;328bd10f-6f03-454a-8271-3cb3c30f733d&quot; FirstMajorVersion=&quot;1&quot; FirstMinorVersion=&quot;12&quot; LastMajorVersion=&quot;1&quot; LastMinorVersion=&quot;12&quot; PlatformBitmask=&quot;ALL&quot;&gt;
        ///  &lt;CustomScripts /&gt;
        ///  &lt;SchemaName&gt;Case Database Schema&lt;/SchemaName&gt;
        ///  &lt;CaseTables /&gt;
        ///  &lt;GlobalTables&gt;
        ///    &lt;GlobalTableDef FirstMajorVersion=&quot;1&quot; FirstMinorVersion=&quot;12&quot; LastMajorVersion=&quot;1&quot; LastMinorVersion=&quot;12&quot; PlatformBitmask=&quot;ALL&quot;&gt;
        ///      &lt;GlobalTableForeignKeys /&gt;
        ///      &lt;Indexes&gt;
        ///        &lt;IndexDef IndexType=&quot;NONCLUSTERED&quot; Category [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaseSchema {
            get {
                return ResourceManager.GetString("CaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CaseSchema SchemaID=&quot;0575f168-221b-47b8-bedb-aa4d7e03db05&quot; FirstMajorVersion=&quot;1&quot; FirstMinorVersion=&quot;3&quot; LastMajorVersion=&quot;1&quot; LastMinorVersion=&quot;12&quot; PlatformBitmask=&quot;ALL&quot;&gt;
        ///  &lt;CustomScripts /&gt;
        ///  &lt;SchemaName&gt;ULM&lt;/SchemaName&gt;
        ///  &lt;CaseTables /&gt;
        ///  &lt;GlobalTables&gt;
        ///    &lt;GlobalTableDef FirstMajorVersion=&quot;1&quot; FirstMinorVersion=&quot;3&quot; LastMajorVersion=&quot;1&quot; LastMinorVersion=&quot;12&quot; PlatformBitmask=&quot;ALL&quot;&gt;
        ///      &lt;GlobalTableForeignKeys /&gt;
        ///      &lt;Indexes&gt;
        ///        &lt;IndexDef IndexType=&quot;CLUSTERED&quot; Category=&quot;PRIMARYKEY&quot; FirstMaj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ulmschema {
            get {
                return ResourceManager.GetString("ulmschema", resourceCulture);
            }
        }
    }
}
