// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;

using Zen.Utilities;
using Zen.Utilities.Proc;

namespace _TestProject
{
    [TestClass()]
    public class ExecutorTest
    {
        private TestContext testContextInstance;

        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        //[TestMethod()]
        public void RunProcessTest()
        {
            Executor target = new Executor();

            string cmd = "notepad.exe";
            string cmdArguments = @"C:\test.log";
            target.RunProcess(cmd, cmdArguments);

            cmd = "calc.exe";
            cmdArguments = string.Empty;
            target.RunProcess(cmd, cmdArguments);
        }

    }


}
