// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Zen.Utilities.FileUtil;
using System.Collections.Generic;
using Zen.Utilities.Text;

namespace _TestProject
{
    [TestClass()]
    public class RegexTest: TestBase
    {
        [TestMethod()]
        public void ProcessLineTest()
        {
            const string testLine1 = @"a,b,,<web>q<web>,c~,";

            DelimiterInfo di = new DelimiterInfo();
            di.Delimiters = new string[] { ",", "\t", " " };
            di.MarkMap = new Dictionary<string, string>();
            di.MarkMap.Add("~","\r\n");
            di.MarkMap.Add("<web>", "\"");

            DelimitedReader reader = new DelimitedReader(di);
            reader.Feed(testLine1);
        }

        [TestMethod()]
        public void TestRegex()
        {
            string name = "Zhou, Feng";
            string fl = RegexPro.ToFirstNameLastName(name);
            string lf = RegexPro.ToLastNameFirstName(fl);

            Assert.IsTrue(name == lf);
        }
    }
}
