// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace _TestProject
{
    [TestClass()]
    public class TempSqlObjNameGeneratorTest
    {
        private TestContext testContextInstance;

        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        //[TestMethod()]
        public void GetSpNameTest()
        {
            string expected = "[##ZenSp_5c166ac7-de2c-436c-879d-6841fd9576af]";
            string actual = Zen.DBMS.TempSqlObjNameGenerator.GetSpName(true);

            Assert.AreEqual(expected.Substring(0, 8), actual.Substring(0, 8), "Zen.DBMS.TempSqlObjNameGenerator.GetSpName did not return the expected value.");
        }

    }


}
